### PR TITLE
Responsive web design project

### PR DESCRIPTION
**Pull request by asiimwedismas**
In this project we:
- made a responsive design with 2 breakpoints
- added sidebar.
- added cover images.
- added 4 articles.
- used float, grid and flex positioning.

### CODE REVIEW

**Comment by lekegitrepo** [comment]
#### Hi @asiimwedismas and @rindrajosia :clap: :clap: 
#### You did a good job :+1: However, there are few requirements you need to implement before this project can be approved. Check the following comments :point_down: 

**_1. Improve the pull request message. It should contain short detail of what you did in the project._**

**_2. Increase the height of the top 3 articles (a little bit) on the small screen size (mobile)._**

**_3. Elements should be aligned with [float](https://css-tricks.com/all-about-floats/) and [flex](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) or [grid](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/responsive_design/align_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59540217/))_**

**_float is missing in your style rules_**

**_Kindly fix these and submit for review._**

### _Reviewed by Temitayo Adeleke._

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
#### Status: Request changes.

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👋

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Hi Team 👋

Your project looks great @asiimwedismas  and @rindrajosia  👏

However, there are quite a few fixes to be made to make it look even more awesome:

- [ ] Required - Kindly add the `TNW` logo to the top navbar of the your page.
**THIS IS HOW THE ORIGINAL LOOKS**👇
ice_screenshot_20200421-112709

- [ ] Required - Also please remove all inline comments on both your HTML and CSS codebase. It’s better to delete commented code. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)).

- [ ] Required - Also the `TNW` logo in the top left article looks smaller than the way it should. Kindly compare it to the original webpage and increase its size.
**THIS IS YOURS**👇
ice_screenshot_20200421-111607

**THIS IS WHAT IS EXPECTED**👇
ice_screenshot_20200421-111634

- [ ] Required - In addition, also add one more template to the `Apps`, `Gear` and `Tech` section. Please add the section marked `Distract`, refer to the screenshot below.
**SCREENSHOT**👇
ice_screenshot_20200421-112032

**Once more your project looks great.🚀**

Simply fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Comment by rindrajosia** [comment]
Hello, thanks for your feedback. But I don't understand the first requirement because It is impossible for us to add this logo when we scroll it as it needs javascript that's why we have added the TNW logo in the nav top when we resize the screen

**Comment by asiimwedismas** [comment]
the inline comments are simply for documentation purposes so that when we need to work upon a particular section we can just look for the comments that mark where it begins... I don't suppose you would expect us to check out a git history every time we need to look for sections.

Secondly, deleting comments and referring to git history is only supposed to be for "actual code that you think u will need later" not documentation comments...
Thank you

**Review by christianotieno — APPROVED** [review]
# PROJECT APPROVED :champagne:
Excellent job on this project guys. :fireworks:  Keep it up.
##
### The [clone](https://rawcdn.githack.com/asiimwedismas/thnextweb-page/9bbf6c273e2644446a4ad2ee41ad292fd5438f09/index.html) shows good understanding and usage of building with responsive design. 💯 
##
- The cloned page is rendering as it should and meets all the project specifications.
-  The project has a descriptive README.md and is professionally done. Good job with that.
- Pull Request has a meaningful title and a short description. 
- CSS is clean. No linter errors at this point and no bad practices used as well.
- The markup as well has no errors nor warnings to show. Good job with that.
- The repo has followed all the guidelines there are to follow (GitHub flow etc.)

***All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.***
- Congratulations on the splendid job @asiimwedismas & @rindrajosia! :+1:
- You can now merge to master and I wish you all the very best in your next tasks 🥇 
##
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

**Pull request merged**
